language: php
php:
  - '7.2'
services: mysql
cache: bundler
before_install:
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
  - mysql -u root --password="" < Test/bluetape.sql