language: php

php:
  - '7.2'

services: mysql



before_script:
  - cp www/application/config/auth-test.php www/application/config/auth.php
  - cp www/application/config/database-dev.php www/application/config/database.php
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bluetape;'
  - mysql  -e 'USE bluetape; create table transkrip   (id int,
                                                      requestByEmail varchar(128) ,
                                                      requestDateTime datetime ,
                                                      requestType varchar(8) ,
                                                      requestUsage varchar(256) ,
                                                      answer varchar(16) ,
                                                      answeredByEmail varchar(128) ,
                                                      answeredDateTime datetime ,
                                                      answeredMessage varchar(256) );'
  - mysql  -e 'USE bluetape; create table Transkrip   (id int,
                                                      requestByEmail varchar(128) ,
                                                      requestDateTime datetime ,
                                                      requestType varchar(8) ,
                                                      requestUsage varchar(256) ,
                                                      answer varchar(16) ,
                                                      answeredByEmail varchar(128) ,
                                                      answeredDateTime datetime ,
                                                      answeredMessage varchar(256) );'
  - mysql -e 'USE bluetape;create table Bluetape_Userinfo(email varchar(128) ,
                                                          name varchar(256) ,
                                                          lastUpdate datetime );'
  - mysql -e 'USE bluetape;create table bluetape_userinfo(email varchar(128) ,
                                                          name varchar(256) ,
                                                          lastUpdate datetime );'
  - mysql -e 'USE bluetape;create table PerubahanKuliah(id int ,
                                                          requestByEmail varchar(256) ,
                                                          requestDateTime datetime ,
                                                          mataKuliahName varchar(256) ,
                                                          mataKuliahCode varchar(9) ,
                                                          class varchar(1) ,
                                                          changeType varchar(1) ,
                                                          fromDateTime datetime,
                                                          fromRoom varchar(16) ,
                                                          ke varchar(1024) ,
                                                          remarks varchar(256) ,
                                                          answer varchar(16) ,
                                                          answeredByEmail varchar(256),
                                                          answeredDateTime datetime ,
                                                          answeredMessage varchar(256));'
  - mysql -e 'USE bluetape;create table perubahanKuliah(id int ,
                                                          requestByEmail varchar(256) ,
                                                          requestDateTime datetime ,
                                                          mataKuliahName varchar(256) ,
                                                          mataKuliahCode varchar(9) ,
                                                          class varchar(1) ,
                                                          changeType varchar(1) ,
                                                          fromDateTime datetime,
                                                          fromRoom varchar(16) ,
                                                          ke varchar(1024) ,
                                                          remarks varchar(256) ,
                                                          answer varchar(16) ,
                                                          answeredByEmail varchar(256),
                                                          answeredDateTime datetime ,
                                                          answeredMessage varchar(256));'
  - mysql -e 'USE bluetape;create table jadwal_dosen (id int,
                                                      user varchar(256),
                                                      hari int(11) ,
                                                      jam_mulai int(11) ,
                                                      durasi int(11) ,
                                                      jenis varchar(256) ,
                                                      label varchar(100) ,
                                                      lastUpdate datetime);'
  - mysql -e 'USE bluetape;create table Jadwal_dosen (id int,
                                                      user varchar(256),
                                                      hari int(11) ,
                                                      jam_mulai int(11) ,
                                                      durasi int(11) ,
                                                      jenis varchar(256) ,
                                                      label varchar(100) ,
                                                      lastUpdate datetime);'
  - mysql -e "USE bluetape;insert into PerubahanKuliah values 
                            (1, 'rootbluetape@gmail.com', '2019-04-02 09:48:23', 'Teknologi ', 'AIF123', 'A', 'G', '2019-04-02 09:47:00', '09021', '[{\"dateTime\":\"2019-04-05 09:48:00\",\"room\":\"09022\"}]', '', 'confirmed', 'rootbluetape@gmail.com', '2019-04-02 09:58:33', 'oke'),
                            (3, 'rootbluetape@gmail.com', '2019-04-02 14:17:40', 'Multi Agen', 'AIF234', 'A', 'X', '2019-04-04 10:00:00', '09020', '[]', 'Kelas diadakan karena dosen sakit', 'confirmed', 'rootbluetape@gmail.com', '2019-04-02 14:20:55', 'Boleh'),
                            (4, 'rootbluetape@gmail.com', '2019-04-02 14:19:47', 'Jaringan Komputer', 'AIF101', 'A', 'G', '2019-04-05 07:00:00', '09021', '[{\"dateTime\":\"2019-04-12 07:00:00\",\"room\":\"10317\"}]', 'Kelas diganti karena jaya sakit perut', 'confirmed', 'rootbluetape@gmail.com', '2019-04-02 14:21:03', 'Dipersilahkan'),
                            (5, 'rootbluetape@gmail.com', '2019-04-02 14:24:10', 'Proyek Informatika', 'AIF142', 'B', 'X', '2019-04-01 07:00:00', '09016', '[]', 'Kelas ditiadakan karena dosen ada urusan', 'confirmed', 'rootbluetape@gmail.com', '2019-04-02 14:24:20', '');"
  - mysql -e "USE bluetape;insert into perubahanKuliah values 
                            (1, 'rootbluetape@gmail.com', '2019-04-02 09:48:23', 'Teknologi ', 'AIF123', 'A', 'G', '2019-04-02 09:47:00', '09021', '[{\"dateTime\":\"2019-04-05 09:48:00\",\"room\":\"09022\"}]', '', 'confirmed', 'rootbluetape@gmail.com', '2019-04-02 09:58:33', 'oke'),
                            (3, 'rootbluetape@gmail.com', '2019-04-02 14:17:40', 'Multi Agen', 'AIF234', 'A', 'X', '2019-04-04 10:00:00', '09020', '[]', 'Kelas diadakan karena dosen sakit', 'confirmed', 'rootbluetape@gmail.com', '2019-04-02 14:20:55', 'Boleh'),
                            (4, 'rootbluetape@gmail.com', '2019-04-02 14:19:47', 'Jaringan Komputer', 'AIF101', 'A', 'G', '2019-04-05 07:00:00', '09021', '[{\"dateTime\":\"2019-04-12 07:00:00\",\"room\":\"10317\"}]', 'Kelas diganti karena jaya sakit perut', 'confirmed', 'rootbluetape@gmail.com', '2019-04-02 14:21:03', 'Dipersilahkan'),
                            (5, 'rootbluetape@gmail.com', '2019-04-02 14:24:10', 'Proyek Informatika', 'AIF142', 'B', 'X', '2019-04-01 07:00:00', '09016', '[]', 'Kelas ditiadakan karena dosen ada urusan', 'confirmed', 'rootbluetape@gmail.com', '2019-04-02 14:24:20', '');"
  - mysql -e "USE bluetape; insert into Bluetape_Userinfo values 
                            ('7316053@student.unpar.ac.id', 'ANUGRAH JAYA SAKTI', '2019-04-02 09:25:44'),
                            ('anugrahjaya23@gmail.com', 'anugrah jaya', '2019-04-02 04:40:28'),
                            ('muhammmaddipo@gmail.com', 'Muhammad Dipo', '2019-04-02 00:00:00'),
                            ('rootbluetape@gmail.com', 'Root Bluetape', '2019-04-02 09:26:20');"
  - mysql -e "USE bluetape;insert into bluetape_userinfo values 
                            ('7316053@student.unpar.ac.id', 'ANUGRAH JAYA SAKTI', '2019-04-02 09:25:44'),
                            ('anugrahjaya23@gmail.com', 'anugrah jaya', '2019-04-02 04:40:28'),
                            ('muhammmaddipo@gmail.com', 'Muhammad Dipo', '2019-04-02 00:00:00'),
                            ('rootbluetape@gmail.com', 'Root Bluetape', '2019-04-02 09:26:20');"
  - mysql -e "USE bluetape;insert into jadwal_dosen values
                            (2, 'gemini2911f665@gmail.com', 0, 7, 1, 'konsultasi', 'aa', '2019-03-28 08:30:32'),
                            (3, 'gemini2911f665@gmail.com', 0, 7, 1, 'konsultasi', 'aa', '2019-03-28 08:31:58'),
                            (4, 'Dipo1', 4, 13, 5, 'Kelas', 'Update', '2019-03-28 08:32:56'),
                            (5, 'gemini2911f665@gmail.com', 0, 7, 1, 'konsultasi', 'aa', '2019-03-28 08:33:22'),
                            (6, 'anugrahjaya23@gmail.com', 0, 7, 3, 'kelas', 'kelas TBD', '2019-04-02 04:41:56'),
                            (7, 'anugrahjaya23@gmail.com', 0, 11, 4, 'konsultasi', 'kelas TBD', '2019-04-02 04:41:40'),
                            (8, 'rootbluetape@gmail.com', 0, 7, 1, 'konsultasi', 'kelas TBD', '2019-04-02 05:14:49'),
                            (9, 'rootbluetape@gmail.com', 2, 12, 2, 'kelas', 'Kelas pengganti', '2019-04-02 09:11:07'),
                            (10, 'rootbluetape@gmail.com', 0, 13, 3, 'kelas', 'Kelas Proyek Informatika', '2019-04-02 09:13:27'),
                            (11, 'rootbluetape@gmail.com', 4, 7, 3, 'kelas', 'Kelas Jaringan Komputer', '2019-04-02 09:13:43'),
                            (12, 'rootbluetape@gmail.com', 3, 10, 2, 'kelas', 'Kelas Multi Agen', '2019-04-02 09:14:23');"
  - mysql -e "USE bluetape;insert into Jadwal_dosen values
                            (2, 'gemini2911f665@gmail.com', 0, 7, 1, 'konsultasi', 'aa', '2019-03-28 08:30:32'),
                            (3, 'gemini2911f665@gmail.com', 0, 7, 1, 'konsultasi', 'aa', '2019-03-28 08:31:58'),
                            (4, 'Dipo1', 4, 13, 5, 'Kelas', 'Update', '2019-03-28 08:32:56'),
                            (5, 'gemini2911f665@gmail.com', 0, 7, 1, 'konsultasi', 'aa', '2019-03-28 08:33:22'),
                            (6, 'anugrahjaya23@gmail.com', 0, 7, 3, 'kelas', 'kelas TBD', '2019-04-02 04:41:56'),
                            (7, 'anugrahjaya23@gmail.com', 0, 11, 4, 'konsultasi', 'kelas TBD', '2019-04-02 04:41:40'),
                            (8, 'rootbluetape@gmail.com', 0, 7, 1, 'konsultasi', 'kelas TBD', '2019-04-02 05:14:49'),
                            (9, 'rootbluetape@gmail.com', 2, 12, 2, 'kelas', 'Kelas pengganti', '2019-04-02 09:11:07'),
                            (10, 'rootbluetape@gmail.com', 0, 13, 3, 'kelas', 'Kelas Proyek Informatika', '2019-04-02 09:13:27'),
                            (11, 'rootbluetape@gmail.com', 4, 7, 3, 'kelas', 'Kelas Jaringan Komputer', '2019-04-02 09:13:43'),
                            (12, 'rootbluetape@gmail.com', 3, 10, 2, 'kelas', 'Kelas Multi Agen', '2019-04-02 09:14:23');"
  - mysql -e "USE bluetape;insert into transkrip values
                        (1, '7316053@student.unpar.ac.id', '2019-03-26 15:28:58', 'DPS_ID', 'kuliah', 'printed', 'rootbluetape@gmail.com', '2019-04-02 10:06:09', 'oke'),
                        (3, '7316053@student.unpar.ac.id', '2019-04-02 10:21:03', 'LHS', 'kuliah', 'printed', 'rootbluetape@gmail.com', '2019-04-02 14:25:33', 'Belum lunas pembayaran'),
                        (4, '7316053@student.unpar.ac.id', '2019-04-02 14:25:58', 'DPS_EN', 'Untuk beasiswa', 'printed', 'rootbluetape@gmail.com', '2019-04-02 14:26:32', 'Ambil di TU'),
                        (5,	'7316054@student.unpar.ac.id', '2019-04-02 10:21:00',	'LHS', 'kuliah', NULL, 'rootbluetape@gmail.com', '2019-04-02 10:25:00',	'Belum lunas pembayaran'),
                        (6,	'7316091@student.unpar.ac.id', '2019-04-11 7:30:00',	'LHS', 'kuliah', 'printed', 'rootbluetape@gmail.com',	'2019-04-11 18:09:00',	'oke');"
  - mysql -e "USE bluetape;insert into Transkrip values
                        (1, '7316053@student.unpar.ac.id', '2019-03-26 15:28:58', 'DPS_ID', 'kuliah', 'printed', 'rootbluetape@gmail.com', '2019-04-02 10:06:09', 'oke'),
                        (3, '7316053@student.unpar.ac.id', '2019-04-02 10:21:03', 'LHS', 'kuliah', 'printed', 'rootbluetape@gmail.com', '2019-04-02 14:25:33', 'Belum lunas pembayaran'),
                        (4, '7316053@student.unpar.ac.id', '2019-04-02 14:25:58', 'DPS_EN', 'Untuk beasiswa', 'printed', 'rootbluetape@gmail.com', '2019-04-02 14:26:32', 'Ambil di TU'),
                        (5,	'7316054@student.unpar.ac.id', '2019-04-02 10:21:00',	'LHS', 'kuliah', NULL, 'rootbluetape@gmail.com', '2019-04-02 10:25:00',	'Belum lunas pembayaran'),
                        (6,	'7316091@student.unpar.ac.id', '2019-04-11 7:30:00',	'LHS', 'kuliah', 'printed', 'rootbluetape@gmail.com',	'2019-04-11 18:09:00',	'oke');"

script:
- php www/index.php UnitTest