language: php
php:
  - '7.2'
services: mysql
cache: bundler

before_script:
  - cp www/application/config/auth-dev.php www/application/config/auth.php
  - cp www/application/config/database-dev.php www/application/config/database.php
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bluetape;'
  - mysql -e 'USE bluetape;create table Bluetape_Userinfo(email varchar(128),name varchar(256),lastUpdate datetime);'
  - mysql -e 'USE bluetape;create table PerubahanKuliah(id int,requestByEmail varchar(256),requestDateTime datetime);'
  - mysql -e 'USE bluetape;create table jadwal_dosen (id int , user varchar(256), hari int , jam_mulai int , durasi int , jenis varchar(256) , label varchar(100) , lastUpdate datetime );'
script:
- php www/index.php UnitTest
